"""Inner loop runner for training optimization.
One iteration = propose config change → modify train.py → run training → parse val_bpb → keep/discard.
The search behavior is controlled by SearchConfig, which the outer loop modifies.
Structural improvements (Level 2):
  1. Crash memory — track which params caused crashes and warn the LLM in proposals.
  2. Multi-candidate proposal — LLM generates 3 candidates, then picks best, before GPU time.
  3. Quick-test pre-filter — 15-second smoke test before committing to a full training run.
Structural improvements (Level 2 — Round 2):
  4. Fixed quick-test path bug — quick test file now written to work_dir (not iter_dir)
     so that `from prepare import ...` resolves correctly.
  5. Infrastructure vs training crash classification — if quick test fails due to an
     import error or syntax error (infrastructure bug), skip the quick test and go
     straight to full training instead of wrongly recording a crash.
  6. Momentum tracking — track which parameter change directions led to improvements
     and inject this signal into the proposal prompt so the LLM learns from patterns.
Structural improvements (Level 2 — Round 3):
  7. Simulated annealing acceptance — instead of strict greedy keep/discard, accept
     slightly worse results with decreasing probability as iterations progress. This
     enables the search to escape local minima. Temperature starts at 0.01 and cools.
  8. Revert-to-best on stagnation — if no improvement is found for N consecutive
     iterations, revert the working code to the best-known config. This prevents
     the search from drifting too far from the best solution.
Structural improvements (Level 2 — Round 4):
  9. Elite pool — maintain a pool of top-K configs (by val_bpb), not just the single
     best. The pool is shown to the LLM during proposals to help identify patterns
     across good configs and suggest interpolations/extrapolations.
Structural improvements (Level 2 — Round 5):
  10. Automatic crossover candidate — one of the 3 multi-candidates is now automatically
      generated by interpolating between the two best configs in the elite pool. This
      replaces one LLM-generated candidate with a systematic exploration of the space
      between proven good configs, similar to genetic algorithm crossover.
Structural improvements (Level 2 — Round 6):
  11. Adaptive step-size calibration — tracks the magnitude of parameter changes that
      led to improvements vs regressions, and injects recommended step-size ranges into
      the proposal prompt. This prevents the LLM from making changes that are too timid
      (wasting iterations on negligible tweaks) or too aggressive (causing crashes).
      Also adds validation to crossover candidates to prevent generating clearly invalid
      values (e.g., non-power-of-2 batch sizes, values outside observed elite ranges).
Structural improvements (Level 2 — Round 7):
  12. Plateau detection with forced diversification — detects when the search is stuck
      on the same parameters with diminishing returns, and forces the next proposal to
      explore a DIFFERENT parameter set. This breaks the common pattern where the LLM
      keeps making tiny LR tweaks after finding a good LR range, wasting iterations.
Structural improvements (Level 2 — Round 8):
  13. Crossover frequency limiter — crossover is only injected every 3rd iteration, not
      every iteration. This gives the LLM more chances to propose novel ideas instead of
      the LLM always selecting the "safe" crossover candidate. When crossover is not
      injected, the LLM gets all 3 candidate slots for creative proposals.
  14. Exploration budget — every 3rd iteration is marked as a mandatory "exploration"
      turn where the LLM is instructed to try a bold/novel change rather than incremental
      optimization. This ensures the search doesn't get stuck in local optima.
Structural improvements (Level 2 — Round 9):
  15. Risk-aware exploration — replaces the blind "bold exploration" directive with a
      risk-aware one that considers which parameters are safe to explore with short time
      budgets. Architectural parameters (DEPTH, HEAD_DIM) are marked as high-risk since
      they change model capacity and need longer training. Schedule and LR parameters are
      marked as safe for exploration. Also reduces exploration frequency to every 4th
      iteration since most wins come from incremental LR optimization.
  16. Regression-safe acceptance — tightens the SA acceptance to reject changes that
      are more than 0.003 bpb worse, even if SA would accept them. This prevents the
      search from accepting large regressions that waste subsequent iterations trying
      to recover.
Structural improvements (Level 2 — Round 10):
  17. Outer loop freeze limit — limits the outer loop to freezing at most 5 params per
      cycle. Previously it could freeze 11+ params at once, leaving the LLM with almost
      no options. This ensures at least 5+ params remain active even after outer loop
      analysis. The outer loop prompt is also updated to emphasize this constraint.
  18. Improved momentum signal with confidence — momentum signals now include a confidence
      indicator based on sample size and consistency. Low-confidence signals are labeled
      as "tentative" so the LLM doesn't over-react to noisy early data.
Structural improvements (Level 2 — Round 11, Molecular Genetics):
  19. Epistasis mapping — tracks pairwise parameter interaction effects. When two params
      are changed together, measures whether the joint effect is better (synergistic) or
      worse (antagonistic) than the sum of their individual effects. Advises the LLM
      which pairs to change together vs separately.
  20. Gene regulatory network — learns parameter dependency rules from elite config
      correlations. When param A is high in elites, is param B also high (positive
      regulation) or low (negative regulation)? Injects compensatory change recommendations
      so the LLM knows "if you increase LR, also increase WEIGHT_DECAY."
  21. Knockout screen — periodically resets a parameter to its default value to measure
      its importance. Essential parameters (large regression on knockout) are protected;
      dispensable parameters (no effect) can be safely frozen. Injects knockout candidates
      into the multi-candidate pool every 5th iteration.
  22. Transgenic insertion — transplants exact parameter blocks ("operons") from elite
      configs into the current config. Unlike crossover (which interpolates), transgenic
      insertion preserves the internal consistency of proven-good parameter groups. Operons
      include lr_operon (all LRs), schedule_operon (warmup/warmdown/final), etc.
Structural improvements (Level 2 — Round 12, Archaeology/Paleontology):
  23. Stratigraphic record — layer-by-layer reconstruction of how the current config
      was built. Each "kept" iteration forms a stratum. Tracks which parameters are
      ancient/foundation (changed early, never modified since) vs recent/experimental.
      Injects this provenance chain into the proposal prompt so the LLM understands
      which values are battle-tested pillars vs fragile recent additions.
  24. Fossil record / Lazarus taxa — preserves ALL configs ever tried (not just elite
      survivors). Periodically suggests reviving extinct configs that showed strong
      relative improvement or explored parameter regions never revisited. Lazarus
      revival candidates are injected into the multi-candidate pool every 6th iteration.
  25. Context stratigraphy — tracks the full parameter context surrounding each
      successful/failed change. Identifies context-dependent patterns like "increasing
      MATRIX_LR worked when DEPTH<=10 but failed when DEPTH>=12." Helps the LLM
      understand that parameter values are not universally good or bad — their
      effectiveness depends on the surrounding context.
  26. Excavation grid — divides each parameter's plausible range into bins and tracks
      sampling density. Identifies blind spots (bins never sampled) and suggests
      systematic excavation of under-explored regions. Prevents the search from
      clustering around early successes and ignoring potentially good regions.

Structural improvements (Level 2 — Observational Astronomy):
  31. Survey tiling (SDSS-style) — tracks which regions of each parameter's range have
      been "observed" (proposed) vs unexplored ("dark sky"). Divides each parameter into
      bins and reports coverage maps. Guides the LLM to systematically tile the parameter
      sky rather than staring at the same patch repeatedly.
  32. Adaptive optics (noise correction) — estimates the measurement noise floor from
      historical val_bpb variance using median absolute deviation. Computes signal-to-noise
      ratios for each improvement. Warns when deltas are below the "seeing limit" (noise
      floor) and recommends minimum change magnitudes to beat the noise.
  33. Target of opportunity (surprise follow-up) — detects when an improvement contradicts
      the momentum signal (parameter historically hurt but now helped). These "transient
      events" indicate the search may have found a new, better region. Generates alerts
      that direct the LLM to follow up on the surprise instead of returning to routine
      exploration.
  34. Spectral decomposition (per-parameter attribution) — uses historical single-parameter
      experiments as "reference spectra" to decompose multi-parameter results into per-
      parameter contributions. Identifies which parameters are the strongest levers vs
      neutral passengers, improving the quality of all other signals.
  35. Parallax estimation (landscape roughness) — measures how rapidly val_bpb changes per
      unit of parameter change for each parameter. High roughness = jagged landscape
      requiring small steps; low roughness = smooth landscape allowing large steps. Gives
      a physics-based reason for step-size selection beyond what the step-size calibrator
      provides.

Structural improvements (Level 2 — Translation Theory):
  36. Back-translation — tracks the LLM's predicted outcome direction vs actual result.
      When predictions are systematically wrong for a parameter, the LLM's internal model
      of the loss landscape is miscalibrated. Injects calibration errors into the prompt
      so the LLM can correct its reasoning biases.
  37. Semantic equivalence — canonicalizes proposals to (param, direction, magnitude_bin)
      and detects when the LLM re-proposes something already tried under different wording.
      Prevents wasted iterations on semantically identical proposals.
  38. Register adaptation — adaptively switches prompt register (formal/informal/terse)
      based on which style produces the best outcomes. Formal for exploitation, informal
      for exploration, terse for data-driven phases. Switches on stagnation.
  39. Domestication vs foreignization — detects comfort-zone patterns (same param changed
      repeatedly, round-number bias, parameter fixation) and injects foreignization frames
      (ratio thinking, gradient flow, information bottleneck, loss landscape geometry,
      scaling law reasoning) to force novel reasoning.
  40. Post-editing — applies rule-based constraint checks to the LLM's raw proposal before
      committing to a GPU run: batch sizes must be powers of 2, warmup+warmdown<=1.0,
      LRs must be positive, DEPTH must be a positive integer, etc. Fixes safe violations
      automatically and warns the LLM about recurring constraint violations.
"""

from __future__ import annotations

import json
import logging
import math
import random
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from core.llm_client import LLMClient

from .config import HYPERPARAM_NAMES, SearchConfig
from .mechanisms import (
    AdaptiveOptics,
    BackTranslation,
    CompostHeap,
    ContextStratigraphy,
    CrashMemory,
    Domestication,
    ElitePool,
    EpistasisMap,
    ExcavationGrid,
    FossilRecord,
    GeneRegulatoryNetwork,
    KnockoutScreen,
    MomentumTracker,
    ParallaxEstimator,
    PerennialClassifier,
    PlateauDetector,
    PostEditing,
    RegisterAdaptation,
    SeasonalCycling,
    SemanticEquivalence,
    SoilHealthMonitor,
    SpectralDecomposition,
    StepSizeCalibrator,
    StratigraphicRecord,
    SurveyTiling,
    TargetOfOpportunity,
    TransgenicInsertion,
)

logger = logging.getLogger(__name__)



# ---------------------------------------------------------------------------
# Data classes

# ---------------------------------------------------------------------------



@dataclass
class TrainResult:
    iteration: int
    val_bpb: float
    peak_vram_mb: float
    training_seconds: float
    num_params_m: float
    status: str  # "keep" | "discard" | "crash"
    changes: dict  # param_name -> new_value
    description: str
    depth: int = 0





@dataclass
class TrainTrace:
    results: list[TrainResult] = field(default_factory=list)
    best_bpb: float = float("inf")
    best_iteration: int = 0



    def add(self, result: TrainResult) -> None:
        self.results.append(result)
        if result.status == "keep" and result.val_bpb < self.best_bpb:
            self.best_bpb = result.val_bpb
            self.best_iteration = result.iteration



    def summary(self, last_n: int = 10) -> str:
        lines = [f"Best: {self.best_bpb:.6f} (iter {self.best_iteration})"]
        for r in self.results[-last_n:]:
            lines.append(
                f"  iter {r.iteration}: bpb={r.val_bpb:.6f} [{r.status}] {r.description}"
            )

        return "\n".join(lines)





# ---------------------------------------------------------------------------
# Prompts

# ---------------------------------------------------------------------------



PROPOSE_SYSTEM = """You are an autonomous ML researcher optimizing a GPT pretraining script.
Your goal: get the lowest val_bpb (validation bits per byte).
You modify hyperparameters in train.py. Each run trains for a fixed time budget.
Return valid JSON only."""



PROPOSE_PROMPT = """\
## Current Hyperparameters
{current_config}



## Experiment History
{trace_summary}



## Search Configuration
Strategy: {strategy}
Active parameters (you may change ONLY these): {active_params}
Frozen parameters (do NOT touch): {frozen_params}



{guidance}



{crash_warnings}



{momentum_signals}



## Task
Propose ONE change to the hyperparameters. Pick the single most promising modification.



Return JSON:
{{
  "changes": {{
    "PARAM_NAME": new_value
  }},
  "hypothesis": "Why this change should improve val_bpb",
  "expected_direction": "lower|higher|uncertain"
}}



Rules:
- Change 1-3 parameters at most
- Only change parameters listed in "Active parameters"
- Values must be valid Python literals (e.g. 0.04, 2**19, "(0.8, 0.95)", "SSSL")
- Be specific about WHY this change should help based on the trace
- Pay close attention to any crash history warnings above
- If momentum signals are available, bias your proposals toward directions that have worked
"""



# Multi-candidate prompt: generate 3 candidates at once
MULTI_CANDIDATE_PROMPT = """\
## Current Hyperparameters
{current_config}



## Experiment History
{trace_summary}



## Search Configuration
Strategy: {strategy}
Active parameters (you may change ONLY these): {active_params}
Frozen parameters (do NOT touch): {frozen_params}



{guidance}



{crash_warnings}



{momentum_signals}



{elite_pool}



{step_size_recs}



{epistasis_signals}



{grn_signals}



{knockout_importance}



{operon_info}



{stratigraphy_info}



{fossil_info}



{context_info}



{excavation_info}



{compost_info}



{soil_health_info}



{seasonal_info}



{perennial_info}

{survey_coverage}

{seeing_conditions}

{too_alert}

{spectral_analysis}

{landscape_roughness}

{calibration_report}

{redundancy_map}

{register_context}

{domestication_context}

{post_edit_constraints}

## Task
Propose THREE different candidate hyperparameter changes. Each candidate should explore
a DIFFERENT parameter or direction. Rank them from most to least promising.



Return JSON:
{{
  "candidates": [
    {{
      "changes": {{"PARAM_NAME": new_value}},
      "hypothesis": "Why this change should improve val_bpb",
      "expected_direction": "lower|higher|uncertain",
      "risk": "low|medium|high"
    }},
    {{
      "changes": {{"PARAM_NAME": new_value}},
      "hypothesis": "...",
      "expected_direction": "...",
      "risk": "..."
    }},
    {{
      "changes": {{"PARAM_NAME": new_value}},
      "hypothesis": "...",
      "expected_direction": "...",
      "risk": "..."
    }}
  ]
}}



Rules:
- Each candidate should change 1-3 parameters at most
- Only change parameters listed in "Active parameters"
- Values must be valid Python literals (e.g. 0.04, 2**19, "(0.8, 0.95)", "SSSL")
- Make candidates genuinely different — explore different parts of the search space
- Pay close attention to any crash history warnings above
- If momentum signals are available, bias at least one candidate toward directions that have worked
- If elite pool is available, use the convergence analysis to identify promising ranges
- If epistasis data is available, use synergistic pairs and avoid antagonistic ones
- If parameter dependency rules are available, apply compensatory changes when adjusting linked params
- If an operon is available, consider changing the whole operon together instead of individual params
- If stratigraphic data is available, be cautious with FOUNDATION params (old/stable) and bolder with RECENT params
- If fossil/Lazarus candidates are available, consider reviving promising extinct directions
- If context patterns are available, choose changes that fit the CURRENT parameter context
- If excavation grid shows blind spots, consider exploring unsampled regions
- If compost analysis shows barren zones, AVOID those value ranges — they have been tested and failed
- If soil health is STRESSED or DEPLETED, follow the remediation directives to restore search health
- If seasonal focus is active, PRIORITIZE the in-season parameter family for at least one candidate
- If perennial/annual classification is available, focus on ANNUAL params — perennials are settled
- If survey coverage shows dark-sky tiles, explore those unexplored regions instead of re-observing over-observed tiles
- If adaptive optics reports a noise floor, only propose changes expected to produce deltas ABOVE the noise threshold
- If a Target of Opportunity alert is active, follow up on the surprise discovery before returning to routine exploration
- If spectral analysis identifies strong/weak levers, concentrate effort on the strongest lever parameters
- If landscape roughness data is available, use SMALL steps for rough parameters and LARGE steps for smooth ones
- If back-translation calibration shows poor prediction accuracy for a parameter, reconsider your assumptions about it
- If the redundancy map shows over-tested regions, do NOT re-propose changes in those regions
- If a register context is specified, follow the thinking style it prescribes
- If a domestication/foreignization frame is active, adopt the alternative reasoning frame instead of your default
- If post-editing constraints are listed, ensure your proposal satisfies ALL of them to avoid auto-correction
"""



# Picker prompt: given 3 candidates, pick the best one
PICK_CANDIDATE_PROMPT = """\
You are selecting the best hyperparameter change to run next. Training takes several
minutes of GPU time, so pick carefully.



## Current Best val_bpb: {best_bpb}



## Candidates:
{candidates_text}



## Selection Criteria:
1. Most likely to IMPROVE val_bpb (lower is better)
2. Low risk of crashing (OOM, timeout, divergence)
3. Novel — not repeating something already tried in the history



Pick the index (0, 1, or 2) of the best candidate.



Return JSON:
{{
  "pick": 0,
  "reasoning": "Why this candidate is the best choice"
}}
"""





# ---------------------------------------------------------------------------
# Infrastructure error detection (Level 2 Round 2 — Improvement 5)

# ---------------------------------------------------------------------------



INFRA_ERROR_PATTERNS = [
    "ModuleNotFoundError",
    "ImportError",
    "SyntaxError",
    "IndentationError",
    "FileNotFoundError",
    "PermissionError",
    "No module named",
]





def _is_infrastructure_error(stderr: str) -> bool:
    """Check if a crash was caused by infrastructure (not training).



    Infrastructure errors are things like missing imports, syntax errors, etc.
    that indicate a bug in the runner, NOT a bad hyperparameter choice.
    These should NOT be recorded as crashes in crash memory.
    """

    for pattern in INFRA_ERROR_PATTERNS:
        if pattern in stderr:
            return True
    return False





# ---------------------------------------------------------------------------
# Runner

# ---------------------------------------------------------------------------



class TrainRunner:
    """Runs the inner loop: propose → modify train.py → train → evaluate → keep/discard."""



    # Quick-test parameters
    QUICK_TEST_BUDGET = 15  # seconds for smoke test
    QUICK_TEST_LOSS_THRESHOLD = 20.0  # loss above this after 15s = likely diverging



    def __init__(
        self,
        train_py: Path,
        work_dir: Path,
        llm_client: LLMClient,
        search_config: SearchConfig | None = None,
        artifacts_dir: Path | None = None,
        simple_mode: bool = False,
    ):
        self.train_py = Path(train_py)
        self.work_dir = Path(work_dir)
        self.client = llm_client
        self.search_config = search_config or SearchConfig()
        self.artifacts_dir = artifacts_dir or (self.work_dir / "artifacts" / "train_opt")
        self.simple_mode = simple_mode
        self.artifacts_dir.mkdir(parents=True, exist_ok=True)



        # Read the original train.py
        self.original_code = self.train_py.read_text(encoding="utf-8")
        self.current_code = self.original_code
        self.trace = TrainTrace()



        # Improvement 1: Crash memory
        self.crash_memory = CrashMemory()



        # Improvement 6: Momentum tracking
        self.momentum = MomentumTracker()



        # Improvement 9: Elite pool
        self.elite_pool = ElitePool(max_size=5)



        # Improvement 11: Step-size calibrator
        self.step_calibrator = StepSizeCalibrator()



        # Improvement 12: Plateau detector
        self.plateau_detector = PlateauDetector(window=4, min_improvement_threshold=0.0003)



        # Improvement 19: Epistasis mapping
        self.epistasis_map = EpistasisMap(min_samples_individual=2, min_samples_pair=1)



        # Improvement 20: Gene regulatory network
        self.grn = GeneRegulatoryNetwork(min_elites=3)



        # Improvement 21: Knockout screen
        self.knockout_screen = KnockoutScreen()



        # Improvement 22: Transgenic insertion
        self.transgenic = TransgenicInsertion()



        # Improvement 23: Stratigraphic record (archaeology)
        self.stratigraphy = StratigraphicRecord()



        # Improvement 24: Fossil record / Lazarus taxa (paleontology)
        self.fossil_record = FossilRecord(max_fossils=30)



        # Improvement 25: Context stratigraphy (archaeological context analysis)
        self.context_stratigraphy = ContextStratigraphy(min_observations=3)



        # Improvement 26: Excavation grid (systematic spatial sampling)
        self.excavation_grid = ExcavationGrid()



        # Improvement 27: Compost heap (permaculture — extract value from failures)
        self.compost_heap = CompostHeap(min_failures_for_zone=2)



        # Improvement 28: Soil health monitor (permaculture — holistic search health)
        self.soil_health = SoilHealthMonitor(lookback_window=8)



        # Improvement 29: Seasonal cycling (permaculture — crop rotation through param families)
        self.seasonal_cycling = SeasonalCycling(season_length=3)



        # Improvement 30: Perennial classifier (permaculture — settled vs volatile params)
        self.perennial_classifier = PerennialClassifier(min_trials=3, convergence_threshold=0.05)

        # Improvement 31: Survey tiling (astronomy — SDSS-style parameter sky coverage)
        self.survey_tiling = SurveyTiling()

        # Improvement 32: Adaptive optics (astronomy — measurement noise correction)
        self.adaptive_optics = AdaptiveOptics(min_samples=3)

        # Improvement 33: Target of opportunity (astronomy — follow up on surprises)
        self.target_of_opportunity = TargetOfOpportunity(cooldown=3, surprise_threshold=0.001)

        # Improvement 34: Spectral decomposition (astronomy — per-parameter attribution)
        self.spectral_decomposition = SpectralDecomposition(min_solo_samples=1)

        # Improvement 35: Parallax estimator (astronomy — landscape roughness)
        self.parallax_estimator = ParallaxEstimator(min_observations=3)

        # Improvement 36: Back-translation (translation theory — prediction calibration)
        self.back_translation = BackTranslation(min_samples=3, error_threshold=0.002)

        # Improvement 37: Semantic equivalence (translation theory — deduplication)
        self.semantic_equivalence = SemanticEquivalence(max_history=50)

        # Improvement 38: Register adaptation (translation theory — prompt style)
        self.register_adaptation = RegisterAdaptation(switch_window=4, min_samples_per_register=2)

        # Improvement 39: Domestication vs foreignization (translation theory — comfort zone)
        self.domestication = Domestication(comfort_threshold=3, foreignize_cooldown=4)

        # Improvement 40: Post-editing (translation theory — constraint enforcement)
        self.post_editing = PostEditing()

        # Improvement 21: Knockout frequency (inject knockout candidate every Nth iteration)
        self._knockout_frequency = 5



        # Improvement 13: Crossover frequency limiter
        self._crossover_frequency = 3  # inject crossover every Nth iteration
        self._proposal_count = 0



        # Improvement 14+15: Exploration budget (risk-aware)
        self._exploration_frequency = 4  # force exploration every Nth iteration



        # Improvement 16: Regression-safe max delta
        self._max_acceptable_regression = 0.003  # reject regressions larger than this



        # Improvement 7: Simulated annealing acceptance
        self._sa_initial_temp = 0.008  # initial temperature (in bpb units)
        self._sa_cooling_rate = 0.7    # temperature multiplied by this each iteration
        self._sa_temp = self._sa_initial_temp
        self._sa_iteration_count = 0



        # Improvement 8: Revert-to-best on stagnation
        self._best_code: str | None = None   # code corresponding to best bpb
        self._iters_since_improvement = 0
        self._stagnation_threshold = 3       # revert after this many non-improving iters



    def run_iteration(self, iteration: int) -> TrainResult:
        """Run one inner loop iteration."""

        iter_dir = self.artifacts_dir / f"iter_{iteration:03d}"
        iter_dir.mkdir(parents=True, exist_ok=True)



        current_config = self._extract_hyperparams(self.current_code)
        logger.info(f"[Iter {iteration}] Proposing changes...")



        # 1. LLM proposes changes (multi-candidate with picker)
        proposal = self._propose(current_config, iteration)
        (iter_dir / "proposal.json").write_text(
            json.dumps(proposal, indent=2), encoding="utf-8"
        )



        if not proposal.get("changes"):
            logger.warning(f"[Iter {iteration}] No changes proposed")
            return TrainResult(
                iteration=iteration, val_bpb=self.trace.best_bpb,
                peak_vram_mb=0, training_seconds=0, num_params_m=0,
                status="discard", changes={}, description="No changes proposed",
            )

        # Improvement 36: Record back-translation prediction before GPU run
        if not self.simple_mode:
            self.back_translation.record_prediction(
                changes=proposal["changes"],
                expected_direction=proposal.get("expected_direction", "uncertain"),
                hypothesis=proposal.get("hypothesis", ""),
            )

        # Improvement 40: Post-edit the proposal (fix constraint violations)
        if not self.simple_mode:
            post_edit_result = self.post_editing.post_edit(
                changes=proposal["changes"],
                current_config=current_config,
            )
            if post_edit_result["corrections"]:
                logger.info(
                    f"[Iter {iteration}] Post-editing corrected: "
                    + ", ".join(
                        f"{c['param']}: {c['original']} -> {c['corrected']} ({c['rule']})"
                        for c in post_edit_result["corrections"]
                    )
                )
            if post_edit_result["warnings"]:
                for w in post_edit_result["warnings"]:
                    logger.warning(f"[Iter {iteration}] Post-edit warning: {w}")
            proposal["changes"] = post_edit_result["changes"]

        # 2. Apply changes to train.py
        new_code = self._apply_changes(self.current_code, proposal["changes"])
        new_code = self._inject_time_budget(new_code)
        modified_path = self.work_dir / "train.py"
        modified_path.write_text(new_code, encoding="utf-8")
        (iter_dir / "train.py").write_text(new_code, encoding="utf-8")



        # 3. Quick-test pre-filter (Improvement 3, fixed in Improvement 4)
        # Skipped in simple_mode — go directly to full training
        if not self.simple_mode:
            logger.info(f"[Iter {iteration}] Running quick test (15s)... (changes: {proposal['changes']})")
            quick_result = self._run_training(
                modified_path, iter_dir, quick_test=True
            )



            if quick_result is None:
                # Quick test crashed — check if it's an infrastructure error
                quicktest_err_path = iter_dir / "quicktest_error.txt"
                if quicktest_err_path.exists():
                    err_text = quicktest_err_path.read_text(encoding="utf-8")
                    if _is_infrastructure_error(err_text):
                        # Infrastructure error: skip quick test, go straight to full run
                        logger.warning(
                            f"[Iter {iteration}] Quick test had INFRASTRUCTURE error "
                            f"(not a training crash) — skipping quick test, trying full run"
                        )

                    else:
                        # Real training crash
                        logger.warning(f"[Iter {iteration}] Quick test CRASHED — skipping full run")
                        self.crash_memory.record(
                            proposal["changes"], iteration, error_hint="crashed in 15s smoke test"
                        )

                        r = TrainResult(
                            iteration=iteration, val_bpb=0, peak_vram_mb=0,
                            training_seconds=0, num_params_m=0, status="crash",
                            changes=proposal["changes"],
                            description=f"CRASH (quick test): {proposal.get('hypothesis', '')}",
                        )

                        self.trace.add(r)
                        return r
                else:
                    # No error file — could be timeout or other issue, skip quick test
                    logger.warning(
                        f"[Iter {iteration}] Quick test failed without error file — "
                        f"skipping quick test, trying full run"
                    )

            elif quick_result.get("quick_test_diverged"):
                # Loss was abnormally high — skip full run
                logger.warning(
                    f"[Iter {iteration}] Quick test DIVERGING (loss={quick_result.get('val_bpb', '?')}) "
                    f"— skipping full run"
                )

                self.crash_memory.record(
                    proposal["changes"], iteration, error_hint="diverging loss in 15s smoke test"
                )

                r = TrainResult(
                    iteration=iteration, val_bpb=0, peak_vram_mb=0,
                    training_seconds=0, num_params_m=0, status="crash",
                    changes=proposal["changes"],
                    description=f"DIVERGED (quick test): {proposal.get('hypothesis', '')}",
                )

                self.trace.add(r)
                return r
            else:
                logger.info(f"[Iter {iteration}] Quick test passed — proceeding to full training")



        # 4. Full training run
        logger.info(f"[Iter {iteration}] Training... (changes: {proposal['changes']})")
        result = self._run_training(modified_path, iter_dir)



        if result is None:
            # Crash during full run
            logger.warning(f"[Iter {iteration}] Training crashed")
            # Record in crash memory (Improvement 1)
            self.crash_memory.record(
                proposal["changes"], iteration, error_hint="timeout/OOM in full training"
            )

            r = TrainResult(
                iteration=iteration, val_bpb=0, peak_vram_mb=0,
                training_seconds=0, num_params_m=0, status="crash",
                changes=proposal["changes"],
                description=f"CRASH: {proposal.get('hypothesis', '')}",
            )

            self.trace.add(r)
            return r



        # 5. Keep/discard decision
        best_before = self.trace.best_bpb
        is_better = result["val_bpb"] < self.trace.best_bpb



        if is_better:
            # Strictly better — always keep
            status = "keep"
            self.current_code = new_code
            self._best_code = new_code
            self._iters_since_improvement = 0
            logger.info(
                f"[Iter {iteration}] KEEP (improved): {result['val_bpb']:.6f} "
                f"(was {self.trace.best_bpb:.6f}, delta={self.trace.best_bpb - result['val_bpb']:.6f})"
            )

        elif self.simple_mode:

            # simple_mode: binary keep/discard — no SA, no revert-to-best
            status = "discard"
            logger.info(
                f"[Iter {iteration}] DISCARD: {result['val_bpb']:.6f} "
                f"(best={self.trace.best_bpb:.6f})"
            )

        else:
            # Worse result — use simulated annealing to decide (Improvement 7)
            delta = result["val_bpb"] - self.trace.best_bpb  # positive = worse
            self._sa_iteration_count += 1
            self._sa_temp = self._sa_initial_temp * (self._sa_cooling_rate ** self._sa_iteration_count)



            # Improvement 16: Reject large regressions outright
            if delta > self._max_acceptable_regression:
                accept_prob = 0.0
                logger.info(
                    f"[Iter {iteration}] Regression too large ({delta:+.6f} > {self._max_acceptable_regression}) — auto-reject"
                )

            elif self._sa_temp > 1e-6:

                # SA acceptance probability: exp(-delta / temperature)
                accept_prob = math.exp(-delta / self._sa_temp)
            else:
                accept_prob = 0.0



            if random.random() < accept_prob:
                # SA accepted — keep code to enable exploration, but DON'T update best
                status = "keep"
                # SA accepted
                self.current_code = new_code
                self._iters_since_improvement += 1
                logger.info(
                    f"[Iter {iteration}] KEEP (SA accepted, p={accept_prob:.3f}, T={self._sa_temp:.6f}): "
                    f"{result['val_bpb']:.6f} (best={self.trace.best_bpb:.6f}, delta={delta:+.6f})"
                )

            else:
                status = "discard"
                self._iters_since_improvement += 1
                logger.info(
                    f"[Iter {iteration}] DISCARD (SA rejected, p={accept_prob:.3f}, T={self._sa_temp:.6f}): "
                    f"{result['val_bpb']:.6f} (best={self.trace.best_bpb:.6f})"
                )



            # Improvement 8: Revert-to-best on stagnation
            if self._iters_since_improvement >= self._stagnation_threshold and self._best_code is not None:
                logger.info(
                    f"[Iter {iteration}] REVERT-TO-BEST: {self._iters_since_improvement} iterations "
                    f"without improvement — reverting to best config (bpb={self.trace.best_bpb:.6f})"
                )

                self.current_code = self._best_code
                self._iters_since_improvement = 0

                # Reset SA temperature to allow fresh exploration from best
                self._sa_temp = self._sa_initial_temp * 0.5



        r = TrainResult(
            iteration=iteration,
            val_bpb=result["val_bpb"],
            peak_vram_mb=result.get("peak_vram_mb", 0),
            training_seconds=result.get("training_seconds", 0),
            num_params_m=result.get("num_params_m", 0),
            status=status,
            changes=proposal["changes"],
            description=proposal.get("hypothesis", ""),
            depth=result.get("depth", 0),
        )

        self.trace.add(r)



        # Record momentum signal (Improvement 6)
        self.momentum.record(
            changes=proposal["changes"],
            old_config=current_config,
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )



        # Record step-size calibration (Improvement 11)
        self.step_calibrator.record(
            changes=proposal["changes"],
            old_config=current_config,
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )



        # Record plateau detection (Improvement 12)
        self.plateau_detector.record(
            changes=proposal["changes"],
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )



        # Record epistasis mapping (Improvement 19)
        self.epistasis_map.record(
            changes=proposal["changes"],
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )



        # Record stratigraphic record (Improvement 23)
        self.stratigraphy.record(
            iteration=iteration,
            changes=proposal["changes"],
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )



        # Record context stratigraphy (Improvement 25)
        self.context_stratigraphy.record(
            changes=proposal["changes"],
            old_config=current_config,
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )

        # Record compost heap (Improvement 27 — permaculture)
        self.compost_heap.record(
            changes=proposal["changes"],
            old_config=current_config,
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )

        # Record soil health (Improvement 28 — permaculture)
        self.soil_health.record(
            changes=proposal["changes"],
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
            iteration=iteration,
        )

        # Advance seasonal cycling and record harvest (Improvement 29 — permaculture)
        self.seasonal_cycling.advance()
        self.seasonal_cycling.record_harvest(
            changes=proposal["changes"],
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
        )

        # Record perennial classifier (Improvement 30 — permaculture)
        self.perennial_classifier.record(
            changes=proposal["changes"],
            val_bpb=result["val_bpb"],
            best_bpb_before=best_before,
            status=status,
            iteration=iteration,
        )

        # Record in elite pool (Improvement 9)
        if status != "crash":
            result_config = self._extract_hyperparams(new_code)
            self.elite_pool.add(
                val_bpb=result["val_bpb"],
                config=result_config,
                iteration=iteration,
                description=proposal.get("hypothesis", ""),
            )



            # Record GRN observation (Improvement 20)
            self.grn.record_config(
                config=result_config,
                val_bpb=result["val_bpb"],
                was_improvement=(result["val_bpb"] < best_before),
            )



            # Update knockout screen with current config (Improvement 21)
            self.knockout_screen.set_current_config(result_config)



            # Check if this was a knockout experiment and record result
            knockout_param = self.knockout_screen.is_knockout_proposal(proposal["changes"])
            if knockout_param is not None:
                knockout_delta = result["val_bpb"] - best_before
                self.knockout_screen.record_knockout(knockout_param, knockout_delta)
                logger.info(
                    f"[Iter {iteration}] Knockout result for {knockout_param}: "
                    f"delta={knockout_delta:+.6f}"
                )



            # Rebuild GRN rules periodically (every 5 iterations with enough elites)
            if iteration > 0 and iteration % 5 == 0 and len(self.elite_pool._pool) >= 3:
                elite_configs = [
                    (bpb, cfg) for bpb, cfg, _, _ in self.elite_pool._pool
                ]
                self.grn.build_rules(elite_configs)



            # Record fossil record (Improvement 24) — ALL configs, not just elites
            self.fossil_record.record(
                iteration=iteration,
                changes=proposal["changes"],
                val_bpb=result["val_bpb"],
                best_bpb_before=best_before,
                status=status,
                config_snapshot=result_config,
            )



            # Record excavation grid position (Improvement 26)
            self.excavation_grid.record(
                config=result_config,
                val_bpb=result["val_bpb"],
            )

        # Record survey tiling observation (Improvement 31)
        self.survey_tiling.record(
            changes=proposal["changes"],
            old_config=current_config,
        )

        # Record adaptive optics observation (Improvement 32)
        if status != "crash":
            self.adaptive_optics.record(
                val_bpb=result["val_bpb"],
                status=status,
                changes=proposal["changes"],
            )

        # Check for target of opportunity (Improvement 33)
        if status != "crash" and result["val_bpb"] < best_before:
            surprise = self.target_of_opportunity.check_surprise(
                changes=proposal["changes"],
                val_bpb=result["val_bpb"],
                best_bpb_before=best_before,
                iteration=iteration,
                momentum_signals=self.momentum._signals,
            )
            if surprise:
                logger.info(
                    f"[Iter {iteration}] TARGET OF OPPORTUNITY: {surprise['param']} "
                    f"surprise improvement={surprise['improvement']:.6f}"
                )
        elif self.target_of_opportunity._active_too is not None:
            # Clear the alert after a non-improving follow-up
            if iteration - self.target_of_opportunity._active_too["iteration"] >= 2:
                self.target_of_opportunity.clear_alert()

        # Record spectral decomposition (Improvement 34)
        if status != "crash":
            self.spectral_decomposition.record_from_changes(
                changes=proposal["changes"],
                val_bpb=result["val_bpb"],
                best_bpb_before=best_before,
                status=status,
            )
            # Decompose multi-parameter results for insight
            if len(proposal["changes"]) >= 2:
                delta = result["val_bpb"] - best_before
                attributions = self.spectral_decomposition.decompose(
                    changes=proposal["changes"],
                    total_delta=delta,
                )
                if attributions:
                    logger.info(
                        f"[Iter {iteration}] Spectral decomposition: "
                        f"{', '.join(f'{p}={a:+.6f}' for p, a in attributions.items())}"
                    )

        # Record parallax observation (Improvement 35)
        if status != "crash":
            self.parallax_estimator.record(
                changes=proposal["changes"],
                old_config=current_config,
                val_bpb=result["val_bpb"],
                status=status,
            )

        # Record back-translation outcome (Improvement 36)
        if not self.simple_mode:
            self.back_translation.record_outcome(
                changes=proposal["changes"],
                val_bpb=result["val_bpb"],
                best_bpb_before=best_before,
                status=status,
            )

        # Record semantic equivalence (Improvement 37)
        if not self.simple_mode:
            self.semantic_equivalence.record(
                changes=proposal["changes"],
                old_config=current_config,
                iteration=iteration,
                hypothesis=proposal.get("hypothesis", ""),
                val_bpb=result["val_bpb"],
                best_bpb_before=best_before,
                status=status,
            )

        # Record register adaptation (Improvement 38)
        if not self.simple_mode:
            self.register_adaptation.record(
                val_bpb=result["val_bpb"],
                best_bpb_before=best_before,
                status=status,
                iteration=iteration,
            )

        # Record domestication tracking (Improvement 39)
        if not self.simple_mode:
            self.domestication.record(
                changes=proposal["changes"],
                iteration=iteration,
            )

        # Save trace
        (iter_dir / "result.json").write_text(
            json.dumps({"val_bpb": r.val_bpb, "status": r.status,
                        "changes": r.changes, "description": r.description},
                       indent=2), encoding="utf-8"
        )



        return r



    def run_baseline(self) -> TrainResult:
        """Run the unmodified train.py to establish baseline."""

        logger.info("[Baseline] Running unmodified train.py...")
        iter_dir = self.artifacts_dir / "baseline"
        iter_dir.mkdir(parents=True, exist_ok=True)



        # Write current (possibly SDPA-patched) train.py with time budget override
        code = self._inject_time_budget(self.current_code)
        modified_path = self.work_dir / "train.py"
        modified_path.write_text(code, encoding="utf-8")



        result = self._run_training(modified_path, iter_dir)
        if result is None:
            raise RuntimeError("Baseline training crashed!")



        r = TrainResult(
            iteration=0, val_bpb=result["val_bpb"],
            peak_vram_mb=result.get("peak_vram_mb", 0),
            training_seconds=result.get("training_seconds", 0),
            num_params_m=result.get("num_params_m", 0),
            status="keep", changes={}, description="baseline",
            depth=result.get("depth", 0),
        )

        self.trace.add(r)

        # Initialize best code for revert-to-best (Improvement 8)
        self._best_code = self.current_code

        # Add baseline to elite pool (Improvement 9)
        baseline_config = self._extract_hyperparams(self.current_code)
        self.elite_pool.add(r.val_bpb, baseline_config, 0, "baseline")

        # Initialize knockout screen with default values (Improvement 21)
        self.knockout_screen.set_defaults(baseline_config)
        self.knockout_screen.set_current_config(baseline_config)

        # Initialize GRN with baseline observation (Improvement 20)
        self.grn.record_config(baseline_config, r.val_bpb, was_improvement=False)

        # Initialize excavation grid with baseline position (Improvement 26)
        self.excavation_grid.record(config=baseline_config, val_bpb=r.val_bpb)
        logger.info(f"[Baseline] val_bpb={r.val_bpb:.6f}, params={r.num_params_m:.1f}M")
        return r



    # ------------------------------------------------------------------
    # Private

    # ------------------------------------------------------------------



    def _propose(self, current_config: dict, iteration: int) -> dict:
        """Ask LLM to propose hyperparameter changes.



        Uses multi-candidate proposal (Improvement 2):
        1. LLM generates 3 candidates in one call.
        2. LLM picks the best candidate in a second call.
        This filters bad ideas with ~1 extra LLM call instead of wasting GPU time.



        Falls back to single-proposal mode if multi-candidate parsing fails.
        """

        from core.llm_client import parse_json_response



        self._proposal_count += 1



        crash_warnings = self.crash_memory.get_warning_text()
        guidance = self.search_config.guidance



        if self.simple_mode:

            # simple_mode: skip all Level 2 mechanisms — use single PROPOSE_PROMPT directly
            prompt = PROPOSE_PROMPT.format(
                current_config=json.dumps(current_config, indent=2),
                trace_summary=self.trace.summary(),
                strategy=self.search_config.strategy,
                active_params=", ".join(self.search_config.active_params),
                frozen_params=", ".join(self.search_config.frozen_params) or "(none)",
                guidance=guidance,
                crash_warnings=crash_warnings,
                momentum_signals="",
            )

            raw = self.client.call(prompt, system=PROPOSE_SYSTEM, max_tokens=1000)
            result = parse_json_response(raw)
            if not isinstance(result, dict) or "raw_content" in result:
                logger.warning(f"[Iter {iteration}] Failed to parse proposal: {raw[:200]}")
                return {"changes": {}, "hypothesis": "parse failure"}
            changes = result.get("changes", {})
            active = set(self.search_config.active_params)
            filtered = {k: v for k, v in changes.items() if k in active}
            if len(filtered) < len(changes):
                dropped = set(changes) - active
                logger.warning(f"[Iter {iteration}] Dropped frozen params from proposal: {dropped}")
            result["changes"] = filtered
            return result



        momentum_signals = self.momentum.get_momentum_text()
        elite_pool_text = self.elite_pool.get_elite_text()
        step_size_text = self.step_calibrator.get_step_size_text()
        epistasis_text = self.epistasis_map.get_epistasis_text()
        grn_text = self.grn.get_grn_text()
        knockout_text = self.knockout_screen.get_importance_text()
        operon_text = self.transgenic.get_operon_text()
        stratigraphy_text = self.stratigraphy.get_stratigraphy_text()
        fossil_text = self.fossil_record.get_fossil_text()
        context_text = self.context_stratigraphy.get_context_text()
        excavation_text = self.excavation_grid.get_excavation_text()
        compost_text = self.compost_heap.get_compost_text()
        soil_health_text = self.soil_health.get_health_text(self.search_config.active_params)
        seasonal_text = self.seasonal_cycling.get_season_text(self.search_config.active_params)
        perennial_text = self.perennial_classifier.get_perennial_text(self.search_config.active_params)
        survey_text = self.survey_tiling.get_coverage_text()
        seeing_text = self.adaptive_optics.get_seeing_text()
        too_text = self.target_of_opportunity.get_too_text()
        spectral_text = self.spectral_decomposition.get_attribution_text()
        roughness_text = self.parallax_estimator.get_roughness_text()
        calibration_text = self.back_translation.get_calibration_text()
        redundancy_text = self.semantic_equivalence.get_redundancy_summary()
        register_text = self.register_adaptation.get_register_text()
        domestication_text = self.domestication.get_domestication_text(iteration)
        post_edit_text = self.post_editing.get_post_edit_text()

        # Improvement 12: Check for plateau and inject diversification directive
        is_plateau, plateau_directive = self.plateau_detector.check_plateau()
        if is_plateau:
            guidance = guidance + "\n" + plateau_directive
            logger.info(f"[Iter {iteration}] PLATEAU DETECTED — forcing diversification")



        # Improvement 14+15: Exploration budget — risk-aware exploration
        is_exploration_turn = (self._proposal_count % self._exploration_frequency == 0)
        if is_exploration_turn and not is_plateau:
            exploration_directive = (
                "\n## EXPLORATION TURN (risk-aware)\n"
                "This is a mandatory exploration iteration. Try a parameter you haven't changed recently.\n"
                "\nSAFE to explore (low risk with short training runs):\n"
                "- WEIGHT_DECAY, WARMUP_RATIO, WARMDOWN_RATIO, FINAL_LR_FRAC — schedule params\n"
                "- EMBEDDING_LR, UNEMBEDDING_LR — secondary LR params\n"
                "- ADAM_BETAS — optimizer momentum\n"
                "\nDANGEROUS to explore (high risk with short training runs):\n"
                "- DEPTH — changes model capacity dramatically, needs longer training to converge\n"
                "- TOTAL_BATCH_SIZE — large changes cause gradient scale mismatch\n"
                "- HEAD_DIM — changes model architecture fundamentally\n"
                "\nMake a MODERATE change to a safe-to-explore parameter you haven't tried recently."
            )

            guidance = guidance + "\n" + exploration_directive
            logger.info(f"[Iter {iteration}] EXPLORATION TURN — risk-aware exploration")



        # --- Attempt multi-candidate proposal ---
        multi_prompt = MULTI_CANDIDATE_PROMPT.format(
            current_config=json.dumps(current_config, indent=2),
            trace_summary=self.trace.summary(),
            strategy=self.search_config.strategy,
            active_params=", ".join(self.search_config.active_params),
            frozen_params=", ".join(self.search_config.frozen_params) or "(none)",
            guidance=guidance,
            crash_warnings=crash_warnings,
            momentum_signals=momentum_signals,
            elite_pool=elite_pool_text,
            step_size_recs=step_size_text,
            epistasis_signals=epistasis_text,
            grn_signals=grn_text,
            knockout_importance=knockout_text,
            operon_info=operon_text,
            stratigraphy_info=stratigraphy_text,
            fossil_info=fossil_text,
            context_info=context_text,
            excavation_info=excavation_text,
            survey_coverage=survey_text,
            seeing_conditions=seeing_text,
            too_alert=too_text,
            spectral_analysis=spectral_text,
            landscape_roughness=roughness_text,
            calibration_report=calibration_text,
            redundancy_map=redundancy_text,
            register_context=register_text,
            domestication_context=domestication_text,
            post_edit_constraints=post_edit_text,
            compost_info=compost_text,
            soil_health_info=soil_health_text,
            seasonal_info=seasonal_text,
            perennial_info=perennial_text,
        )



        raw = self.client.call(multi_prompt, system=PROPOSE_SYSTEM, max_tokens=2000)
        multi_result = parse_json_response(raw)



        candidates = None
        if isinstance(multi_result, dict) and "candidates" in multi_result:
            raw_candidates = multi_result["candidates"]
            if isinstance(raw_candidates, list) and len(raw_candidates) >= 2:
                # Validate each candidate has changes
                valid = [c for c in raw_candidates if isinstance(c, dict) and c.get("changes")]
                if len(valid) >= 2:
                    candidates = valid[:3]  # cap at 3



        if candidates:
            # Improvement 10+13: Inject crossover candidate from elite pool
            # (only every Nth iteration to give LLM more creative slots)
            is_crossover_turn = (self._proposal_count % self._crossover_frequency == 0)



            # Improvement 21: Inject knockout candidate every Nth iteration
            is_knockout_turn = (self._proposal_count % self._knockout_frequency == 0)



            # Improvement 22: Alternate between crossover and transgenic insertion
            # Even crossover turns use classic crossover, odd ones use transgenic
            use_transgenic = (self._proposal_count // self._crossover_frequency) % 2 == 1



            if is_knockout_turn and not is_exploration_turn:
                # Knockout takes priority — it's a diagnostic experiment
                knockout = self.knockout_screen.suggest_knockout(
                    self.search_config.active_params
                )

                if knockout and len(candidates) >= 3:
                    logger.info(f"[Iter {iteration}] Injecting knockout candidate: {knockout['changes']}")
                    candidates[-1] = knockout
                elif knockout and len(candidates) < 3:
                    candidates.append(knockout)
                    logger.info(f"[Iter {iteration}] Added knockout candidate: {knockout['changes']}")
                else:
                    logger.info(f"[Iter {iteration}] No knockout candidate available")
            elif is_crossover_turn and not is_exploration_turn:
                if use_transgenic:
                    # Improvement 22: Transgenic insertion — transplant exact operon
                    elite_configs = [
                        (bpb, cfg) for bpb, cfg, _, _ in self.elite_pool._pool
                    ]
                    transgenic = self.transgenic.generate_transgenic_candidate(
                        current_config, elite_configs, self.search_config.active_params
                    )

                    if transgenic and len(candidates) >= 3:
                        logger.info(f"[Iter {iteration}] Injecting transgenic candidate: {transgenic['changes']}")
                        candidates[-1] = transgenic
                    elif transgenic and len(candidates) < 3:
                        candidates.append(transgenic)
                        logger.info(f"[Iter {iteration}] Added transgenic candidate: {transgenic['changes']}")
                    else:
                        # Fallback to classic crossover if transgenic not possible
                        crossover = self.elite_pool.generate_crossover(
                            current_config, self.search_config.active_params
                        )

                        if crossover and len(candidates) >= 3:
                            logger.info(f"[Iter {iteration}] Injecting crossover (transgenic unavailable): {crossover['changes']}")
                            candidates[-1] = crossover
                        elif crossover and len(candidates) < 3:
                            candidates.append(crossover)
                else:
                    # Classic crossover
                    crossover = self.elite_pool.generate_crossover(
                        current_config, self.search_config.active_params
                    )

                    if crossover and len(candidates) >= 3:
                        logger.info(f"[Iter {iteration}] Injecting crossover candidate: {crossover['changes']}")
                        candidates[-1] = crossover
                    elif crossover and len(candidates) < 3:
                        candidates.append(crossover)
                        logger.info(f"[Iter {iteration}] Added crossover candidate: {crossover['changes']}")
            else:
                # Improvement 24+26: On non-crossover/knockout turns, try
                # Lazarus revival (every 6th) or excavation (every 7th)
                is_lazarus_turn = (self._proposal_count % 6 == 0)
                is_excavation_turn = (self._proposal_count % 7 == 0)



                injected = False
                if is_lazarus_turn and not is_exploration_turn:
                    revival = self.fossil_record.suggest_revival(
                        current_config, self.trace.best_bpb,
                        self.search_config.active_params,
                    )

                    if revival:
                        if len(candidates) >= 3:
                            candidates[-1] = revival
                        else:
                            candidates.append(revival)
                        logger.info(f"[Iter {iteration}] Injecting Lazarus revival candidate: {revival['changes']}")
                        injected = True



                if not injected and is_excavation_turn and not is_exploration_turn:
                    excavation = self.excavation_grid.suggest_excavation(
                        current_config, self.search_config.active_params,
                    )

                    if excavation:
                        if len(candidates) >= 3:
                            candidates[-1] = excavation
                        else:
                            candidates.append(excavation)
                        logger.info(f"[Iter {iteration}] Injecting excavation candidate: {excavation['changes']}")
                        injected = True



                if not injected:
                    logger.info(f"[Iter {iteration}] Skipping crossover/transgenic/knockout/lazarus/excavation (proposal #{self._proposal_count})")



            logger.info(f"[Iter {iteration}] Got {len(candidates)} candidates, asking LLM to pick best")



            # Build picker prompt
            candidates_text_lines = []
            for i, c in enumerate(candidates):
                candidates_text_lines.append(
                    f"### Candidate {i}\n"
                    f"Changes: {json.dumps(c['changes'])}\n"
                    f"Hypothesis: {c.get('hypothesis', 'N/A')}\n"
                    f"Risk: {c.get('risk', 'unknown')}\n"
                )

            candidates_text = "\n".join(candidates_text_lines)



            pick_prompt = PICK_CANDIDATE_PROMPT.format(
                best_bpb=f"{self.trace.best_bpb:.6f}",
                candidates_text=candidates_text,
            )



            pick_raw = self.client.call(pick_prompt, system=PROPOSE_SYSTEM, max_tokens=500)
            pick_result = parse_json_response(pick_raw)



            picked_idx = 0  # default to first (most promising) if parsing fails
            if isinstance(pick_result, dict) and "pick" in pick_result:
                try:
                    idx = int(pick_result["pick"])
                    if 0 <= idx < len(candidates):
                        picked_idx = idx
                except (ValueError, TypeError):
                    pass



            chosen = candidates[picked_idx]
            logger.info(
                f"[Iter {iteration}] Picked candidate {picked_idx}: {chosen['changes']} "
                f"(reason: {pick_result.get('reasoning', 'N/A')[:100]})"
            )



            # Validate: only active params
            changes = chosen.get("changes", {})
            active = set(self.search_config.active_params)
            filtered = {k: v for k, v in changes.items() if k in active}
            if len(filtered) < len(changes):
                dropped = set(changes) - active
                logger.warning(f"[Iter {iteration}] Dropped frozen params from proposal: {dropped}")
            chosen["changes"] = filtered



            return chosen



        # --- Fallback: single proposal (original behavior) ---
        logger.info(f"[Iter {iteration}] Multi-candidate failed, falling back to single proposal")



        prompt = PROPOSE_PROMPT.format(
            current_config=json.dumps(current_config, indent=2),
            trace_summary=self.trace.summary(),
            strategy=self.search_config.strategy,
            active_params=", ".join(self.search_config.active_params),
            frozen_params=", ".join(self.search_config.frozen_params) or "(none)",
            guidance=guidance,
            crash_warnings=crash_warnings,
            momentum_signals=momentum_signals,
        )



        raw = self.client.call(prompt, system=PROPOSE_SYSTEM, max_tokens=1000)
        result = parse_json_response(raw)



        if not isinstance(result, dict) or "raw_content" in result:
            logger.warning(f"[Iter {iteration}] Failed to parse proposal: {raw[:200]}")
            return {"changes": {}, "hypothesis": "parse failure"}



        # Validate: only active params
        changes = result.get("changes", {})
        active = set(self.search_config.active_params)
        filtered = {k: v for k, v in changes.items() if k in active}
        if len(filtered) < len(changes):
            dropped = set(changes) - active
            logger.warning(f"[Iter {iteration}] Dropped frozen params from proposal: {dropped}")
        result["changes"] = filtered



        return result



    def _apply_changes(self, code: str, changes: dict) -> str:
        """Replace hyperparameter values in train.py code."""

        for param, value in changes.items():
            # Match lines like: PARAM_NAME = value  # comment
            pattern = rf'^({re.escape(param)}\s*=\s*)(.+?)(\s*#.*)?$'
            safe_value = str(value).replace('\\', '\\\\')
            replacement = rf'\g<1>{safe_value}\3'
            code = re.sub(pattern, replacement, code, count=1, flags=re.MULTILINE)
        return code



    def _inject_time_budget(self, code: str, override_budget: int | None = None) -> str:
        """Override TIME_BUDGET if search_config specifies a non-default value.



        Idempotent — safe to call multiple times on the same code.



        Args:
            override_budget: If set, use this value instead of search_config.time_budget.
                             Used by quick-test to inject a 15-second budget.
        """

        budget = override_budget if override_budget is not None else self.search_config.time_budget
        if budget != 300:
            # Step 1: Ensure the import uses `as _TIME_BUDGET` alias
            if "TIME_BUDGET as _TIME_BUDGET" not in code:
                code = code.replace(
                    "from prepare import MAX_SEQ_LEN, TIME_BUDGET,",
                    "from prepare import MAX_SEQ_LEN, TIME_BUDGET as _TIME_BUDGET,",
                    1,
                )



            # Step 2: Remove any existing override lines (idempotent cleanup)
            code = re.sub(
                r'\nTIME_BUDGET = \d+\s*#[^\n]*\n',
                '\n',
                code,
            )



            # Step 3: Insert the override ONCE before the GPT Model section
            code = code.replace(
                "# ---------------------------------------------------------------------------\n# GPT Model",
                f"TIME_BUDGET = {budget}  # overridden by bilevel runner\n\n"
                "# ---------------------------------------------------------------------------\n# GPT Model",
                1,
            )

        return code



    def _extract_hyperparams(self, code: str) -> dict:
        """Parse current hyperparameter values from train.py code."""

        config = {}
        for param in HYPERPARAM_NAMES:
            pattern = rf'^{re.escape(param)}\s*=\s*(.+?)(?:\s*#.*)?$'
            match = re.search(pattern, code, re.MULTILINE)
            if match:
                config[param] = match.group(1).strip()
        return config



    def _run_training(
        self, train_path: Path, iter_dir: Path, quick_test: bool = False
    ) -> dict | None:
        """Execute train.py and parse results. Returns None on crash.



        Args:
            quick_test: If True, run a 15-second smoke test instead of full training.
                        Returns dict with 'quick_test_diverged' key if loss is abnormally high.
        """

        if quick_test:
            # Improvement 4: Write quick test to work_dir (not iter_dir) so that
            # `from prepare import ...` resolves correctly. The previous bug wrote
            # the file to iter_dir (inside artifacts/) where prepare.py doesn't exist.
            code = self._apply_changes(
                self.current_code,
                self._extract_changes_from_file(train_path),
            )

            code = self._inject_time_budget(code, override_budget=self.QUICK_TEST_BUDGET)

            # Write to work_dir so imports resolve correctly
            quick_path = self.work_dir / "train_quicktest.py"
            quick_path.write_text(code, encoding="utf-8")
            # Also save a copy in iter_dir for debugging
            (iter_dir / "train_quicktest.py").write_text(code, encoding="utf-8")
            run_path = quick_path
            log_name = "quicktest.log"
            timeout = self.QUICK_TEST_BUDGET * 6  # 90s max for 15s test (compile overhead)
        else:
            run_path = train_path
            log_name = "run.log"
            timeout = self.search_config.time_budget * 3



        log_path = iter_dir / log_name



        try:
            # Use the work_dir's .venv python if available (has torch),
            # otherwise fall back to current interpreter
            venv_python = self.work_dir / ".venv" / "bin" / "python"
            python_cmd = str(venv_python) if venv_python.exists() else sys.executable
            result = subprocess.run(
                [python_cmd, str(run_path)],
                capture_output=True, text=True,
                timeout=timeout,
                cwd=str(self.work_dir),
            )

            log_path.write_text(result.stdout + "\n" + result.stderr, encoding="utf-8")



            if result.returncode != 0:
                logger.warning(
                    f"Training failed (exit {result.returncode})"
                    f"{' [quick test]' if quick_test else ''}"
                )

                (iter_dir / ("quicktest_error.txt" if quick_test else "error.txt")).write_text(
                    result.stderr[-2000:], encoding="utf-8"
                )

                return None



            parsed = self._parse_results(result.stdout)



            if quick_test and parsed is not None:
                # Check for divergence: abnormally high loss or NaN
                val_bpb = parsed.get("val_bpb", 0)
                if val_bpb != val_bpb:  # NaN check
                    parsed["quick_test_diverged"] = True
                    logger.warning("[Quick test] NaN detected in val_bpb")
                elif val_bpb > self.QUICK_TEST_LOSS_THRESHOLD:
                    parsed["quick_test_diverged"] = True
                    logger.warning(f"[Quick test] Loss {val_bpb:.4f} > threshold {self.QUICK_TEST_LOSS_THRESHOLD}")
                else:
                    parsed["quick_test_diverged"] = False



            # For quick test, if parsing fails entirely, check stderr for FAIL/OOM signals
            if quick_test and parsed is None:
                output = result.stdout + result.stderr
                if any(kw in output.upper() for kw in ["FAIL", "OOM", "OUT OF MEMORY", "NAN", "CUDA ERROR"]):
                    return None
                # No val_bpb but no obvious error — could be too short to produce output
                # Treat as passing (not enough data to judge)
                return {"val_bpb": 0, "quick_test_diverged": False}



            return parsed



        except subprocess.TimeoutExpired:
            logger.warning(f"Training timed out{' [quick test]' if quick_test else ''}")
            return None
        except Exception as e:
            logger.warning(f"Training error: {e}")
            return None



    def _extract_changes_from_file(self, train_path: Path) -> dict:
        """Extract the hyperparameter changes applied to a modified train.py file.



        Compares the modified file against self.current_code to find what changed.
        """

        modified_code = train_path.read_text(encoding="utf-8")
        current_config = self._extract_hyperparams(self.current_code)
        modified_config = self._extract_hyperparams(modified_code)
        changes = {}
        for param in modified_config:
            if param in current_config and modified_config[param] != current_config[param]:
                changes[param] = modified_config[param]
        return changes



    def _parse_results(self, stdout: str) -> dict | None:
        """Parse val_bpb and other metrics from training output."""

        metrics = {}
        for line in stdout.splitlines():
            for key in ["val_bpb", "peak_vram_mb", "training_seconds",
                        "num_params_M", "depth", "total_seconds"]:
                if line.startswith(f"{key}:"):
                    try:
                        val = float(line.split(":")[1].strip())
                        # Normalize key names
                        norm_key = key.lower().replace("_m", "_m")
                        if key == "num_params_M":
                            norm_key = "num_params_m"
                        metrics[norm_key] = val
                    except (ValueError, IndexError):
                        pass



        if "val_bpb" not in metrics:
            return None
        return metrics

