"""Skill Promoter — converts high-confidence lessons into reusable agent skills.

This is the key emergent behavior of EvoResearch:
  Run → Review → Lessons → (promote) → Skills → injected into future runs/agents

Skills are different from lessons:
- Lessons: specific observations from a single run
- Skills: distilled, generalized, reusable prompt templates for agents

Skills are saved to memory/skills/ as markdown files, one per stage domain.
They can be:
  1. Injected into future pipeline stages (in addition to lessons)
  2. Used directly by agents as prompt templates
  3. Exported as Claude Code skill files
"""
from collections import defaultdict
from pathlib import Path

from ..llm_client import call_llm
from .lesson_schema import Lesson

PROMOTION_SYSTEM = """You are a research methodology expert.
Your task: distill a set of empirically-discovered lessons into a concise, reusable skill.
The skill must be actionable, specific, and directly usable as an agent instruction."""

PROMOTION_PROMPT = """The following lessons were extracted from multiple AI research pipeline runs.
They represent patterns discovered through trial and error.

Stage: {stage}
Lessons:
{lessons_text}

Synthesize these into a concise SKILL DEFINITION — a reusable prompt template
that any agent can follow to avoid these failure patterns and replicate successes.

Format:
## Skill: {stage_title}

### When to apply
(one sentence: when should an agent use this skill?)

### Core rules
(3-7 bullet points: the essential, non-negotiable rules derived from the lessons)

### Anti-patterns to avoid
(2-4 bullet points: what specifically NOT to do)

### Checklist before proceeding
(a concrete checklist the agent can tick off before completing this stage)

Be specific and concrete. Reference the actual patterns found in the lessons."""


# Stage display names
STAGE_TITLES = {
    "hypothesis_generation": "Hypothesis Generation",
    "experiment_plan_or_code": "Experiment Design",
    "draft_writeup": "Research Writeup",
    "literature_scan": "Literature Scan",
    "experiment_result_summary": "Result Reporting",
}


class SkillPromoter:
    def __init__(self, memory_dir: Path, min_confidence: float = 0.8):
        self.memory_dir = Path(memory_dir)
        self.skills_dir = self.memory_dir / "skills"
        self.skills_dir.mkdir(parents=True, exist_ok=True)
        self.min_confidence = min_confidence

    def promote_all(self, lessons: list[Lesson]) -> dict[str, Path]:
        """
        Promote high-confidence lessons to reusable skills, grouped by stage.
        Returns {stage_name: skill_file_path}.
        """
        # Filter to high-confidence lessons
        eligible = [l for l in lessons if l.confidence >= self.min_confidence]
        if not eligible:
            return {}

        # Group by stage
        by_stage: dict[str, list[Lesson]] = defaultdict(list)
        for lesson in eligible:
            by_stage[lesson.stage].append(lesson)

        promoted = {}
        for stage, stage_lessons in by_stage.items():
            skill_path = self._promote_stage(stage, stage_lessons)
            if skill_path:
                promoted[stage] = skill_path

        # Generate master skill index
        self._write_index(promoted)
        return promoted

    def _promote_stage(self, stage: str, lessons: list[Lesson]) -> Path | None:
        """Generate a skill file for a single stage from its lessons."""
        if len(lessons) < 1:
            return None

        lessons_text = "\n\n".join(
            f"[{l.lesson_type.upper()} | {l.confidence:.0%} confidence]\n"
            f"Summary: {l.summary}\n"
            f"Reuse Rule: {l.reuse_rule}\n"
            f"Anti-Pattern: {l.anti_pattern or 'N/A'}"
            for l in sorted(lessons, key=lambda x: -x.confidence)
        )

        stage_title = STAGE_TITLES.get(stage, stage.replace("_", " ").title())
        prompt = PROMOTION_PROMPT.format(
            stage=stage,
            stage_title=stage_title,
            lessons_text=lessons_text,
        )

        skill_content = call_llm(prompt, system=PROMOTION_SYSTEM, max_tokens=1500)

        # Add metadata header
        source_ids = [l.id for l in lessons]
        avg_confidence = sum(l.confidence for l in lessons) / len(lessons)
        full_content = (
            f"<!-- Auto-generated by EvoResearch SkillPromoter -->\n"
            f"<!-- Stage: {stage} | Lessons: {len(lessons)} | Avg confidence: {avg_confidence:.0%} -->\n"
            f"<!-- Sources: {', '.join(source_ids)} -->\n\n"
            + skill_content
        )

        skill_path = self.skills_dir / f"{stage}.md"
        skill_path.write_text(full_content, encoding="utf-8")
        return skill_path

    def _write_index(self, promoted: dict[str, Path]) -> None:
        """Write a master index of all promoted skills."""
        lines = [
            "# EvoResearch Promoted Skills",
            "",
            "These skills were automatically distilled from empirical research run lessons.",
            "High-confidence patterns that repeated across runs have been promoted to reusable skill templates.",
            "",
        ]
        for stage, path in sorted(promoted.items()):
            title = STAGE_TITLES.get(stage, stage)
            lines.append(f"- **[{title}]({path.name})** — `{stage}`")

        index_path = self.skills_dir / "INDEX.md"
        index_path.write_text("\n".join(lines), encoding="utf-8")

    def load_skill(self, stage: str) -> str:
        """Load a promoted skill for a stage, or return empty string."""
        skill_path = self.skills_dir / f"{stage}.md"
        if skill_path.exists():
            content = skill_path.read_text(encoding="utf-8")
            # Strip metadata comments
            lines = [l for l in content.splitlines() if not l.startswith("<!--")]
            return "\n".join(lines).strip()
        return ""

    def list_skills(self) -> list[dict]:
        """List all promoted skills with metadata."""
        skills = []
        for f in self.skills_dir.glob("*.md"):
            if f.name == "INDEX.md":
                continue
            content = f.read_text(encoding="utf-8")
            # Extract metadata from comments
            stage = f.stem
            meta = {"stage": stage, "path": str(f), "size": len(content)}
            for line in content.splitlines():
                if "Lessons:" in line:
                    try:
                        meta["lesson_count"] = int(line.split("Lessons:")[1].split("|")[0].strip())
                    except Exception:
                        pass
                if "Avg confidence:" in line:
                    try:
                        meta["avg_confidence"] = line.split("Avg confidence:")[1].strip().rstrip("-->").strip()
                    except Exception:
                        pass
            skills.append(meta)
        return skills
